# Generated by Django 5.0.1 on 2024-01-02 20:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=20)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('image_hotel', models.ImageField(blank=True, null=True, upload_to='hotel_rest/')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentInfoRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_of_beds', models.CharField(max_length=30)),
                ('total_area', models.PositiveIntegerField()),
                ('number_of_bathroom', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('price', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('image_apartment', models.ImageField(blank=True, null=True, upload_to='apartment_rest/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel_rest.hotelrest')),
            ],
        ),
    ]
