# Generated by Django 5.0 on 2023-12-29 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentinforest',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='hotelrest',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='hotelrest',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='hotelrest',
            name='photo_country',
        ),
        migrations.AddField(
            model_name='apartmentinforest',
            name='apartment_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hotel_rest.apartmentrest'),
            preserve_default=False,
        ),
    ]
