# Generated by Django 5.0 on 2023-12-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinforest',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='hotel_rest.apartmentrest'),
        ),
    ]
