# Generated by Django 5.0 on 2024-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rest', '0002_alter_apartmentinforest_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentinforest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
