# Generated by Django 4.2.9 on 2024-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rest', '0002_apartmentinforest_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
