# Generated by Django 5.0.1 on 2024-01-05 21:16

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
