# Generated by Django 5.0 on 2023-12-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='hotel',
        ),
        migrations.AddField(
            model_name='apartment',
            name='hotel_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HotelApartment',
        ),
    ]
