# Generated by Django 5.0 on 2023-12-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_apartment_hotel_apartment_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='apartment',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hotel.apartment'),
            preserve_default=False,
        ),
    ]
