# Generated by Django 5.0 on 2023-12-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_apartment_hotel_id_hotel_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='apartment',
        ),
        migrations.CreateModel(
            name='HotelApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.apartment')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='apartment',
            field=models.ManyToManyField(through='hotel.HotelApartment', to='hotel.apartment'),
        ),
    ]
