# Generated by Django 5.0 on 2023-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_hotel_apartment_hotelapartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
    ]
