# Generated by Django 5.0 on 2023-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo_country',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='numer_of_beds',
            field=models.CharField(max_length=30),
        ),
    ]
