# Generated by Django 5.0 on 2023-12-28 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_photo_country_alter_apartment_numer_of_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
